// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxlX21TiTY73HChYmv_64HI91Yu1vlgMk',
    appId: '1:831114805229:web:1773d429d30979ce6f71e4',
    messagingSenderId: '831114805229',
    projectId: 'htrider',
    authDomain: 'htrider.firebaseapp.com',
    storageBucket: 'htrider.appspot.com',
    measurementId: 'G-01QQPSV5LC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqoRUK6BxGjPqRikLmA7iUXDyQQogglmI',
    appId: '1:831114805229:android:bceb1433f090c6cd6f71e4',
    messagingSenderId: '831114805229',
    projectId: 'htrider',
    storageBucket: 'htrider.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_oaCeCbi-n9DKTUOPtYsJYwp_aJdNHXg',
    appId: '1:831114805229:ios:f6eb4f0dbc89e40b6f71e4',
    messagingSenderId: '831114805229',
    projectId: 'htrider',
    storageBucket: 'htrider.appspot.com',
    iosClientId: '831114805229-jme1snh1q81nkipd67j6qsiu8sehmor7.apps.googleusercontent.com',
    iosBundleId: 'com.example.timePe',
  );
}
